spring:
  datasource:
    password: johannesf12
    url: jdbc:mysql://localhost:3306/blog
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
